In [8]:
import pandas as pd
import matplotlib as plt
import numpy as np
from ydata_profiling import ProfileReport
from bs4 import BeautifulSoup as soup
import requests as rq

In [9]:
gram=pd.read_csv(filepath_or_buffer='C:\\Users\DAIR Julia\Desktop\linguistics_capstone\data\grambank\cldf\languages.csv')
gram.drop(['ID', 'ISO639P3code', 'provenance', 'Language_level_ID'], inplace=True, axis=1)

glotto=pd.read_csv(filepath_or_buffer='C:/Users/DAIR Julia/Desktop/linguistics_capstone/data/glottolog_cldf/cldf/languages.csv')
glotto.drop(['ID','Closest_ISO369P3code', 'Language_ID', 'First_Year_Of_Documentation', 'Last_Year_Of_Documentation', 
             'ISO639P3code'], inplace=True, axis=1)

values_df=pd.read_csv(filepath_or_buffer='C:/Users/DAIR Julia/Desktop/linguistics_capstone/data/glottolog_cldf/cldf/values.csv')

codes=pd.read_csv(filepath_or_buffer='C:\\Users\DAIR Julia\Desktop\linguistics_capstone\data\glottolog_cldf\cldf\codes.csv')

In [7]:
pd.read_csv(filepath_or_buffer='C:\\Users\DAIR Julia\Desktop\linguistics_capstone\data\grambank\cldf\parameters.csv')

,ID,Name,Description,ColumnSpec,Patrons,Grambank_ID_desc,Boundness,Flexivity,Gender_or_Noun_Class,Locus_of_Marking,Word_Order,Informativity
0,GB020,Are there definite or specific articles?,## Are there definite or specific articles?\r\...,NaN,JLA JC,GB020 ARTDef,NaN,NaN,NaN,NaN,NaN,definitearticles
1,GB021,Do indefinite nominals commonly have indefinit...,## Do indefinite/non-specific nominals commonl...,NaN,JLA JC,GB021 ARTIndef,NaN,NaN,NaN,NaN,NaN,indef
2,GB022,Are there prenominal articles?,## Are there prenominal articles?\r\n\r\n## Su...,NaN,JLA JC,GB022 ARTPre,NaN,NaN,NaN,NaN,0.0,NaN
3,GB023,Are there postnominal articles?,## Are there postnominal articles?\r\n\r\n## S...,NaN,JLA JC,GB023 ARTPost,NaN,NaN,NaN,NaN,1.0,NaN
4,GB024,What is the order of numeral and noun in the NP?,## What is the order of numeral and noun in th...,NaN,HJH,GB024 NUMOrder,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
190,GB433,Can adnominal possession be marked by a suffix...,## Can adnominal possession be marked by a suf...,NaN,HJH,GB433 POSSSfxPosd,1.0,NaN,NaN,1.0,NaN,NaN
191,GB519,"Can mood be marked by a non-inflecting word (""...",## Can mood be marked by a non-inflecting word...,NaN,HS,GB519 MoodAuxPart,0.0,NaN,NaN,NaN,NaN,mood
192,GB520,Can aspect be marked by a non-inflecting word ...,## Can aspect be marked by a non-inflecting wo...,NaN,HS,GB520 AspectAuxPart,0.0,NaN,NaN,NaN,NaN,aspect
193,GB521,Can tense be marked by a non-inflecting word (...,## Can tense be marked by a non-inflecting wor...,NaN,HS,GB521 TenseAuxPart,0.0,NaN,NaN,NaN,NaN,tense
194,GB522,Can the S or A argument be omitted from a prag...,## Can the S or A argument be omitted from a p...,NaN,HJH,GB522 PRODrop,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
glotto

,Name,Macroarea,Latitude,Longitude,Glottocode,Countries,Family_ID
0,FulniÃ´,South America,-9.025910,-37.140200,fuln1247,BR,NaN
1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN
2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN
3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN
4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN
...,...,...,...,...,...,...,...
26664,Kitsootso,Africa,-5.577220,14.477100,kits1250,NaN,atla1278
26665,Kindamba,Africa,-5.577220,14.477100,kind1243,NaN,atla1278
26666,Kisibemba,Africa,-5.577220,14.477100,kisi1246,NaN,atla1278
26667,Sira,Africa,-1.780840,10.463500,sira1266,GA,atla1278
26668,Barama,Africa,-2.496590,10.677700,bara1362,GA,atla1278

In [ ]:
ProfileReport(gram)

In [ ]:
glotto[glotto['Name'] == 'Abadi']

In [ ]:
#Code to view Glotto fields with high null content:

#glotto[pd.isnull(glotto['Countries'])].head(50)
glotto[pd.isnull(glotto['Macroarea'])].head(50)

In [ ]:
#https:\\en.wal.unesco.org\discover\languages?text=&sort_by=title&page=4

#scrape to get # speakers, and endangered status

page_url='https:\\en.wal.unesco.org\discover\languages?text=&sort_by=title&page=1'
wal_soup = soup(rq.get(page_url).text)


#<a href="https:\\en.wal.unesco.org\lcanguages\akpa" hreflang="en">Akpa<\a>

In [7]:
gram.head()

,Name,Macroarea,Latitude,Longitude,Glottocode,Family_name,Family_level_ID,level,lineage
0,Abadi,Papunesia,-9.03389,146.99200,abad1241,Austronesian,aust1307,language,aust1307/mala1545/cent2237/east2712/ocea1241/west2818/papu1253/peri1258/cent2070/west2850
1,Mungbam,Africa,6.58050,10.22670,abar1238,Atlantic-Congo,atla1278,language,atla1278/volt1241/benu1247/bant1294/sout3152/yemn1234
2,Abau,Papunesia,-3.97222,141.32400,abau1245,Sepik,sepi1257,language,sepi1257
3,AbÃ©,Africa,5.59682,-4.38497,abee1242,Atlantic-Congo,atla1278,language,atla1278/volt1241/kwav1236/nyoa1234/agne1238
4,Abenlen Ayta,Papunesia,15.41310,120.20000,aben1249,Austronesian,aust1307,language,aust1307/mala1545/cent2080/samb1319/abel1234

In [6]:
glotto.head()

,Name,Macroarea,Latitude,Longitude,Glottocode,Countries,Family_ID
0,FulniÃ´,South America,-9.025910,-37.140200,fuln1247,BR,NaN
1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN
2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN
3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN
4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN

In [5]:
pd.set_option('max_colwidth', 300)
values_df.head()

#need to pull from glotto join values, using Language_ID = glottocode, with 'Parameter_ID' like level, category, aes

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,codeReference
0,fuln1247-level,fuln1247,level,language,level-language,NaN,NaN,NaN
1,fuln1247-category,fuln1247,category,Spoken_L1_Language,category-Spoken_L1_Language,NaN,NaN,NaN
2,fuln1247-subclassification,fuln1247,subclassification,"(fuln1248:1,yate1241:1)fuln1247:1;",NaN,NaN,NaN,NaN
3,fuln1247-aes,fuln1247,aes,3,aes-shifting,"YatÃ© (1642-fun) = Threatened (20 percent certain, based on the evidence available) [Crevels 2012](elcat:5ad6b7113e7c6615995bfd4cae2f3f8e)",569683,NaN
4,fuln1247-med,fuln1247,med,0,med-long_grammar,NaN,122653,NaN

In [4]:
codes[codes['Parameter_ID']=='aes']

,ID,Parameter_ID,Name,Description,numerical_value
18,aes-not_endangered,aes,not endangered,EGIDS: <=6a; UNESCO: safe; ElCat: safe,1.0
19,aes-threatened,aes,threatened,EGIDS: 6b; UNESCO: vulnerable; ElCat: vulnerable,2.0
20,aes-shifting,aes,shifting,EGIDS: 7; UNESCO: definitely endangered; ElCat...,3.0
21,aes-moribund,aes,moribund,EGIDS: 8a; UNESCO: severely endangered; ElCat:...,4.0
22,aes-nearly_extinct,aes,nearly extinct,EGIDS: 8b; UNESCO: critically endangered; ElCa...,5.0
23,aes-extinct,aes,extinct,EGIDS: >=9; UNESCO: extinct; ElCat: extinct,6.0

In [ ]:
values_df.shape

In [ ]:
codes.shape

In [8]:
glotto.shape

(26669, 7)

In [ ]:
gram.shape

In [ ]:
values_df['Comment'][values_df['Comment'].notna()].head(40)