In [9]:
import pandas as pd
import matplotlib as plt
import numpy as np
from ydata_profiling import ProfileReport

languages=pd.read_csv('/Users/DAIR Julia/Desktop/linguistics_capstone/languages.csv')
families=pd.read_csv('/Users/DAIR Julia/Desktop/linguistics_capstone/families.csv')

In [16]:
languages.head()

,Unnamed: 0,name,macroarea,latitude,longitude,glottocode,countries,family_id,lineage,level,category,aes
0,0,Fulniô,South America,-9.025910,-37.140200,fuln1247,BR,NaN,NaN,language,Spoken_L1_Language,3.0
1,1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN,NaN,language,Spoken_L1_Language,3.0
2,2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN,NaN,family,Family,NaN
3,3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN,NaN,language,Spoken_L1_Language,6.0
4,4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN,NaN,family,Family,NaN

In [18]:
families['family_id_x'].nunique()

296

| ID |       Parameter_ID | Name |    Description |                                   numerical_value |     |
|---:|-------------------:|-----:|---------------:|--------------------------------------------------:|-----|
| 18 | aes-not_endangered |  aes | not endangered |            EGIDS: <=6a; UNESCO: safe; ElCat: safe | 1.0 |
| 19 |     aes-threatened |  aes |     threatened |  EGIDS: 6b; UNESCO: vulnerable; ElCat: vulnerable | 2.0 |
| 20 |       aes-shifting |  aes |       shifting | EGIDS: 7; UNESCO: definitely endangered; ElCat... | 3.0 |
| 21 |       aes-moribund |  aes |       moribund | EGIDS: 8a; UNESCO: severely endangered; ElCat:... | 4.0 |
| 22 | aes-nearly_extinct |  aes | nearly extinct | EGIDS: 8b; UNESCO: critically endangered; ElCa... | 5.0 |
| 23 |        aes-extinct |  aes |        extinct |       EGIDS: >=9; UNESCO: extinct; ElCat: extinct | 6.0 |

In [18]:
def aes_assignment(x):
        if x == 1:
            return 'Not Endangered'
        if x == 2: 
            return 'Vulnerable'
        if x == 3:
            return 'Shifting'
        if x == 4:
            return 'Moribund'
        if x == 5:
            return 'Nearly Extinct'
        if x == 6:
            return 'Extinct'
        else:
            return 'no status'

languages['aes'] = languages['aes'].apply(aes_assignment)

In [19]:
type(languages['aes'][0])

str

In [ ]:
type(languages['aes'][0])

In [20]:
languages

,Unnamed: 0,name,macroarea,latitude,longitude,glottocode,countries,family_id,lineage,level,category,aes
0,0,Fulniô,South America,-9.025910,-37.140200,fuln1247,BR,NaN,NaN,language,Spoken_L1_Language,Shifting
1,1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN,NaN,language,Spoken_L1_Language,Shifting
2,2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN,NaN,family,Family,no status
3,3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN,NaN,language,Spoken_L1_Language,Extinct
4,4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN,NaN,family,Family,no status
...,...,...,...,...,...,...,...,...,...,...,...,...
26664,26664,Kitsootso,Africa,-5.577220,14.477100,kits1250,NaN,atla1278,NaN,dialect,Dialect,no status
26665,26665,Kindamba,Africa,-5.577220,14.477100,kind1243,NaN,atla1278,NaN,dialect,Dialect,no status
26666,26666,Kisibemba,Africa,-5.577220,14.477100,kisi1246,NaN,atla1278,NaN,dialect,Dialect,no status
26667,26667,Sira,Africa,-1.780840,10.463500,sira1266,GA,atla1278,NaN,language,Spoken_L1_Language,Not Endangered
26668,26668,Barama,Africa,-2.496590,10.677700,bara1362,GA,atla1278,NaN,language,Spoken_L1_Language,Vulnerable

In [21]:
languages

,Unnamed: 0,name,macroarea,latitude,longitude,glottocode,countries,family_id,lineage,level,category,aes
0,0,Fulniô,South America,-9.025910,-37.140200,fuln1247,BR,NaN,NaN,language,Spoken_L1_Language,Shifting
1,1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN,NaN,language,Spoken_L1_Language,Shifting
2,2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN,NaN,family,Family,no status
3,3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN,NaN,language,Spoken_L1_Language,Extinct
4,4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN,NaN,family,Family,no status
...,...,...,...,...,...,...,...,...,...,...,...,...
26664,26664,Kitsootso,Africa,-5.577220,14.477100,kits1250,NaN,atla1278,NaN,dialect,Dialect,no status
26665,26665,Kindamba,Africa,-5.577220,14.477100,kind1243,NaN,atla1278,NaN,dialect,Dialect,no status
26666,26666,Kisibemba,Africa,-5.577220,14.477100,kisi1246,NaN,atla1278,NaN,dialect,Dialect,no status
26667,26667,Sira,Africa,-1.780840,10.463500,sira1266,GA,atla1278,NaN,language,Spoken_L1_Language,Not Endangered
26668,26668,Barama,Africa,-2.496590,10.677700,bara1362,GA,atla1278,NaN,language,Spoken_L1_Language,Vulnerable

In [22]:
languages['aes'].value_counts()

no status         18121
Not Endangered     2957
Shifting           1907
Vulnerable         1558
Extinct            1320
Moribund            450
Nearly Extinct      356
Name: aes, dtype: int64

In [23]:
languages

,Unnamed: 0,name,macroarea,latitude,longitude,glottocode,countries,family_id,lineage,level,category,aes
0,0,Fulniô,South America,-9.025910,-37.140200,fuln1247,BR,NaN,NaN,language,Spoken_L1_Language,Shifting
1,1,Dem,Papunesia,-3.721830,137.632000,demm1245,ID,NaN,NaN,language,Spoken_L1_Language,Shifting
2,2,Mixe-Zoque,NaN,16.991902,-94.207907,mixe1284,NaN,NaN,NaN,family,Family,no status
3,3,Mure,South America,-13.636709,-62.202091,mure1235,BO,NaN,NaN,language,Spoken_L1_Language,Extinct
4,4,North Halmahera,NaN,0.772624,127.656778,nort2923,NaN,NaN,NaN,family,Family,no status
...,...,...,...,...,...,...,...,...,...,...,...,...
26664,26664,Kitsootso,Africa,-5.577220,14.477100,kits1250,NaN,atla1278,NaN,dialect,Dialect,no status
26665,26665,Kindamba,Africa,-5.577220,14.477100,kind1243,NaN,atla1278,NaN,dialect,Dialect,no status
26666,26666,Kisibemba,Africa,-5.577220,14.477100,kisi1246,NaN,atla1278,NaN,dialect,Dialect,no status
26667,26667,Sira,Africa,-1.780840,10.463500,sira1266,GA,atla1278,NaN,language,Spoken_L1_Language,Not Endangered
26668,26668,Barama,Africa,-2.496590,10.677700,bara1362,GA,atla1278,NaN,language,Spoken_L1_Language,Vulnerable

In [24]:
languages.to_csv('languages.csv')